const $ = (selector) => document.querySelector(selector);
const emojis = ['🧟', '🧟‍♀️', '🦇', '🕸️', '🖤', '🪦', '🌙', '⚡', '👻', '🕯️', '💀', '🦴'];
const randomEmoji = () => emojis[Math.floor(Math.random() * emojis.length)];
const dbName = 'my-sounds-db', storeName = 'tracks';
const audio = $('#audio');
let tracks = [], currentId = null, currentUrl = null, db;
let shuffleOn = false, repeatMode = 'off';
function openDB() { return new Promise((resolve,reject)=>{ const request=indexedDB.open(dbName,1); request.onupgradeneeded=()=>request.result.createObjectStore(storeName,{keyPath:'id'}); request.onsuccess=()=>{db=request.result;resolve();};request.onerror=()=>reject(request.error); }); }
function transaction(mode) { return db.transaction(storeName,mode).objectStore(storeName); }
function getAll() { return new Promise((resolve,reject)=>{const request=transaction('readonly').getAll();request.onsuccess=()=>resolve(request.result.sort((a,b)=>b.addedAt-a.addedAt));request.onerror=()=>reject(request.error);}); }
function save(track) { return new Promise((resolve,reject)=>{const request=transaction('readwrite').put(track);request.onsuccess=resolve;request.onerror=()=>reject(request.error);}); }
function remove(id) { return new Promise((resolve,reject)=>{const request=transaction('readwrite').delete(id);request.onsuccess=resolve;request.onerror=()=>reject(request.error);}); }
const formatTime=(seconds)=>!isFinite(seconds)?'0:00':`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
const formatBytes=(bytes)=>bytes<1e6?`${Math.round(bytes/1024)} KB`:`${(bytes/1e6).toFixed(1)} MB`;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('visible'),2600);}
function escapeHTML(value){const el=document.createElement('span');el.textContent=value;return el.innerHTML;}
function render(){const query=$('#searchInput').value.toLowerCase();const list=$('#trackList');const shown=tracks.filter(track=>track.name.toLowerCase().includes(query));$('#libraryCount').textContent=`${tracks.length} ${tracks.length===1?'track':'tracks'}`;list.innerHTML='';$('#emptyState').style.display=tracks.length?'none':'block';shown.forEach(track=>{const emoji=track.emoji||'🧟';const item=document.createElement('article');item.className=`track ${track.id===currentId?'active':''}`;item.innerHTML=`<div class="cover">${emoji}</div><div class="track-info"><div class="track-title">${emoji} ${escapeHTML(track.name)}</div><div class="track-meta">${formatBytes(track.size)} · ${track.type.startsWith('video/')?'Screen recording':'Audio'}</div></div><button class="delete" aria-label="Delete ${escapeHTML(track.name)}">×</button>`;item.querySelector('.track-info').onclick=()=>play(track.id);item.querySelector('.cover').onclick=()=>play(track.id);item.querySelector('.delete').onclick=async(event)=>{event.stopPropagation();if(currentId===track.id)stop();await remove(track.id);tracks=tracks.filter(entry=>entry.id!==track.id);render();toast('Removed from your library');};list.append(item);});if(tracks.length&&!shown.length)list.innerHTML='<p class="empty-state">No matching tracks.</p>';}
async function play(id){const track=tracks.find(entry=>entry.id===id);if(!track)return;if(currentId===id){audio.paused?audio.play():audio.pause();return;}stop();currentId=id;currentUrl=URL.createObjectURL(track.blob);audio.src=currentUrl;$('#nowTitle').textContent=track.name;$('#nowArtist').textContent=track.type.startsWith('video/')?'Screen recording':'Saved on this iPhone';$('#nowCover').textContent=track.emoji||'🧟';$('#player').classList.remove('hidden');audio.play().catch(()=>toast('Tap play to start listening'));render();}
function stop(){audio.pause();audio.removeAttribute('src');audio.load();if(currentUrl)URL.revokeObjectURL(currentUrl);currentUrl=null;currentId=null;}
function currentIndex(){return tracks.findIndex(track=>track.id===currentId);}
function nextTrack(fromEnd=false){if(!tracks.length)return;if(fromEnd&&repeatMode==='one'){audio.currentTime=0;audio.play();return;}const index=currentIndex();if(shuffleOn&&tracks.length>1){const choices=tracks.filter(track=>track.id!==currentId);play(choices[Math.floor(Math.random()*choices.length)].id);return;}const next=index<0?0:index+1;if(next<tracks.length)play(tracks[next].id);else if(repeatMode==='all')play(tracks[0].id);else if(!fromEnd)toast('You are at the end of your library');}
function previousTrack(){if(!tracks.length)return;if(audio.currentTime>3){audio.currentTime=0;return;}const index=currentIndex();if(index>0)play(tracks[index-1].id);else if(repeatMode==='all')play(tracks[tracks.length-1].id);else audio.currentTime=0;}
function updateModes(){$('#shuffleButton').classList.toggle('mode-active',shuffleOn);$('#repeatButton').classList.toggle('mode-active',repeatMode!=='off');$('#repeatButton').textContent=repeatMode==='one'?'↻¹':'↻';$('#repeatButton').setAttribute('aria-label',`Repeat ${repeatMode}`);}
async function importFiles(files){const supported=/\.(mp3|m4a|wav|aac|flac|ogg|opus|mp4|mov|webm)$/i;const valid=[...files].filter(file=>file.type.startsWith('audio/')||file.type.startsWith('video/')||supported.test(file.name));if(!valid.length){toast('Please choose an audio file or recording');return;}try{for(const file of valid)await save({id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),type:file.type||'audio/mpeg',size:file.size,emoji:randomEmoji(),addedAt:Date.now(),blob:file});tracks=await getAll();render();toast(`${valid.length} file${valid.length>1?'s':''} added offline`);}catch(error){toast('Your iPhone is out of storage space');}}
$('#importButton').onclick=()=>$('#fileInput').click();$('#chooseFiles').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=event=>{importFiles(event.target.files);event.target.value='';};$('#searchInput').oninput=render;$('#playButton').onclick=()=>audio.paused?audio.play():audio.pause();$('#previousButton').onclick=previousTrack;$('#nextButton').onclick=()=>nextTrack();$('#backButton').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-10);$('#forwardButton').onclick=()=>audio.currentTime=Math.min(audio.duration,audio.currentTime+10);$('#shuffleButton').onclick=()=>{shuffleOn=!shuffleOn;updateModes();toast(shuffleOn?'Shuffle on':'Shuffle off');};$('#repeatButton').onclick=()=>{repeatMode=repeatMode==='off'?'all':repeatMode==='all'?'one':'off';updateModes();toast(repeatMode==='off'?'Repeat off':repeatMode==='all'?'Repeat all':'Repeat one');};$('#seekBar').oninput=event=>audio.currentTime=(event.target.value/100)*audio.duration;
audio.ontimeupdate=()=>{$('#currentTime').textContent=formatTime(audio.currentTime);$('#seekBar').value=audio.duration?(audio.currentTime/audio.duration)*100:0;};audio.onloadedmetadata=()=>$('#duration').textContent=formatTime(audio.duration);audio.onplay=()=>$('#playButton').textContent='Ⅱ';audio.onpause=()=>$('#playButton').textContent='▶';audio.onended=()=>{$('#playButton').textContent='▶';$('#seekBar').value=0;nextTrack(true);};
const zone=$('#dropZone');['dragenter','dragover'].forEach(event=>zone.addEventListener(event,e=>{e.preventDefault();zone.style.borderColor='#fff';}));['dragleave','drop'].forEach(event=>zone.addEventListener(event,e=>{e.preventDefault();zone.style.borderColor='';}));zone.addEventListener('drop',event=>importFiles(event.dataTransfer.files));
(async()=>{await openDB();tracks=await getAll();render();updateModes();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=5');})();
