const $ = (s) => document.querySelector(s);
const dbName = 'my-sounds-db', storeName = 'tracks';
let tracks = [], currentId = null, currentUrl = null, db;
const audio = $('#audio');

function openDB() { return new Promise((resolve, reject) => { const request = indexedDB.open(dbName, 1); request.onupgradeneeded = () => request.result.createObjectStore(storeName, { keyPath: 'id' }); request.onsuccess = () => { db = request.result; resolve(); }; request.onerror = () => reject(request.error); }); }
function transaction(mode) { return db.transaction(storeName, mode).objectStore(storeName); }
function getAll() { return new Promise((resolve, reject) => { const r = transaction('readonly').getAll(); r.onsuccess = () => resolve(r.result.sort((a,b) => b.addedAt-a.addedAt)); r.onerror = () => reject(r.error); }); }
function save(track) { return new Promise((resolve, reject) => { const r = transaction('readwrite').put(track); r.onsuccess = resolve; r.onerror = () => reject(r.error); }); }
function remove(id) { return new Promise((resolve, reject) => { const r = transaction('readwrite').delete(id); r.onsuccess = resolve; r.onerror = () => reject(r.error); }); }
const formatTime = (s) => !isFinite(s) ? '0:00' : `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const formatBytes = (b) => b < 1e6 ? `${Math.round(b/1024)} KB` : `${(b/1e6).toFixed(1)} MB`;
function toast(message) { const el=$('#toast'); el.textContent=message; el.classList.add('visible'); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.classList.remove('visible'),2600); }

function render() { const query=$('#searchInput').value.toLowerCase(); const list=$('#trackList'); const shown=tracks.filter(t=>t.name.toLowerCase().includes(query)); $('#libraryCount').textContent=`${tracks.length} ${tracks.length===1?'track':'tracks'}`; list.innerHTML=''; $('#emptyState').style.display=tracks.length?'none':'block'; shown.forEach(track=>{ const item=document.createElement('article'); item.className=`track ${track.id===currentId?'active':''}`; item.innerHTML=`<div class="cover">${track.type.startsWith('video/')?'▣':'♫'}</div><div class="track-info"><div class="track-title">${escapeHTML(track.name)}</div><div class="track-meta">${formatBytes(track.size)} · ${track.type.startsWith('video/')?'Screen recording':'Audio'}</div></div><button class="delete" aria-label="Delete ${escapeHTML(track.name)}">×</button>`; item.querySelector('.track-info').onclick=()=>play(track.id); item.querySelector('.cover').onclick=()=>play(track.id); item.querySelector('.delete').onclick=async(e)=>{e.stopPropagation(); if(currentId===track.id) stop(); await remove(track.id); tracks=tracks.filter(t=>t.id!==track.id); render(); toast('Removed from your library');}; list.append(item); }); if(tracks.length && !shown.length) list.innerHTML='<p class="empty-state">No matching tracks.</p>'; }
function escapeHTML(value) { const el=document.createElement('span'); el.textContent=value; return el.innerHTML; }
async function play(id) { const track=tracks.find(t=>t.id===id); if(!track)return; if(currentId===id){ audio.paused?audio.play():audio.pause(); return; } stop(); currentId=id; currentUrl=URL.createObjectURL(track.blob); audio.src=currentUrl; $('#nowTitle').textContent=track.name; $('#nowArtist').textContent=track.type.startsWith('video/')?'Screen recording':'Saved on this iPhone'; $('#player').classList.remove('hidden'); audio.play().catch(()=>toast('Tap play to start listening')); render(); }
function stop() { audio.pause(); audio.removeAttribute('src'); audio.load(); if(currentUrl)URL.revokeObjectURL(currentUrl); currentUrl=null; currentId=null; }
async function importFiles(files) { const valid=[...files].filter(f=>f.type.startsWith('audio/')||f.type.startsWith('video/')); if(!valid.length){toast('Please choose audio or video files');return;} try { for(const file of valid) await save({id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),type:file.type,size:file.size,addedAt:Date.now(),blob:file}); tracks=await getAll(); render(); toast(`${valid.length} file${valid.length>1?'s':''} added offline`); } catch(e) { toast('Your iPhone is out of storage space'); } }
$('#importButton').onclick=()=>$('#fileInput').click(); $('#chooseFiles').onclick=()=>$('#fileInput').click(); $('#fileInput').onchange=(e)=>{importFiles(e.target.files);e.target.value='';}; $('#searchInput').oninput=render;
$('#playButton').onclick=()=>audio.paused?audio.play():audio.pause(); $('#backButton').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-10); $('#forwardButton').onclick=()=>audio.currentTime=Math.min(audio.duration,audio.currentTime+10); $('#seekBar').oninput=(e)=>audio.currentTime=(e.target.value/100)*audio.duration;
audio.ontimeupdate=()=>{ $('#currentTime').textContent=formatTime(audio.currentTime); $('#seekBar').value=audio.duration?(audio.currentTime/audio.duration)*100:0; }; audio.onloadedmetadata=()=>$('#duration').textContent=formatTime(audio.duration); audio.onplay=()=>$('#playButton').textContent='Ⅱ'; audio.onpause=()=>$('#playButton').textContent='▶'; audio.onended=()=>{ $('#playButton').textContent='▶'; $('#seekBar').value=0; };
const zone=$('#dropZone'); ['dragenter','dragover'].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.style.borderColor='#ff5c93';})); ['dragleave','drop'].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.style.borderColor='';})); zone.addEventListener('drop',e=>importFiles(e.dataTransfer.files));
(async()=>{ await openDB(); tracks=await getAll(); render(); if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js'); })();
